export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_ERROR = "LOGIN_ERROR";


export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_POSTS_LOADING = "GET_POSTS_LOADING";
export const GET_POSTS_ERROR = "GET_POSTS_ERROR";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_LOADING = "CREATE_POST_LOADING";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";

export const EDIT_POST = "EDIT_POST";

export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_LOADING = "UPDATE_POST_LOADING";
export const UPDATE_POST_ERROR = "UPDATE_POST_ERROR";


export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_LOADING = "DELETE_POST_LOADING";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";
